## 1. Importing NumPy

NumPy is a Python library used for numerical computing.

It provides a special data structure called **ndarray (N-dimensional array)** which is faster and more powerful than normal Python lists.

We usually import NumPy with the alias `np`.

In [1]:
import numpy as np

## 2. Creating a NumPy Array

A NumPy array is similar to a Python list, but it is optimized for mathematical operations.

Syntax:
np.array()

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## 3. Checking the Type

Let's verify what type of object NumPy creates.

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


## 4. zero Array
Creates an array filled with zeros

In [4]:
zr = np.zeros((3,4))
print(zr)   

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## 5. Ones Array

Creates an array filled with ones

In [9]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


## 6. Full Array

Creates an array filled with a specific value.

In [10]:
full_arr = np.full((2, 2), 7)
print(full_arr)

[[7 7]
 [7 7]]


## 7.Identity Matrix

creates an identity matrix for given dimension .

Very useful in linear algebra and machine learning.

In [11]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 8. arange()

Creates values in a range with a step size.

In [12]:
range_Array = np.arange(0, 10, 2)
print(range_Array)

[0 2 4 6 8]


## 9. linspace( )

Creates evenly spaced numbers between two values.

In [13]:
lin_arr = np.linspace(0, 7, 5)
print(lin_arr)

[0.   1.75 3.5  5.25 7.  ]


## 10. Shape of an Array

Shape tells us how many rows and columns the array has.

In [5]:
print(arr.shape)

(5,)


Meaning of (5,)

This means:

5 elements
1 dimension

## 11. Number of Dimensions

In [6]:
print(arr.ndim)

1


## 12. Total Number of Elements

In [7]:
print(arr.size)

5


## 13. changing data type

Use `astype( )` to convert data types

In [16]:
a1 = np.array([[1,2,3], [4,5,6]])
print(a1.dtype)

a1 = a1.astype('float64')
print(a1.dtype)   

int64
float64


# 14. Repeat and Tile


These are useful for repeating values and patterns.

**Repeat**

In [18]:
repeat_Arr = np.repeat([1,2,3], 9)
print(repeat_Arr)  

[1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3]


**Tile**

In [19]:
tile_Arr = np.tile([1,2,3], 9)
print(tile_Arr)  

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]


## 15. Mathematical Operations

In [8]:
print(arr + 2)
print(arr * 2)
print(arr ** 2)

[3 4 5 6 7]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


**Meaning**

This is where NumPy becomes magical.

Normal Python lists can’t do proper math like this.

NumPy applies operations to every element.

Example:

[1,2,3,4,5]+2=[3,4,5,6,7]

This is called vectorized operation.

Very important term.

It means operate on the whole array at once.

Faster and cleaner.

## Summary

Today I learned:

- what NumPy is
- why arrays are better than lists
- shape
- dimensions
- size
- basic operations

This is the foundation for AI, ML, and data science.