## 1. Importing NumPy

NumPy is a Python library used for numerical computing.

It provides a special data structure called **ndarray (N-dimensional array)** which is faster and more powerful than normal Python lists.

We usually import NumPy with the alias `np`.

In [2]:
import numpy as np

## 2. Creating a NumPy Array

A NumPy array is similar to a Python list, but it is optimized for mathematical operations.

Syntax:
np.array()

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


## 3. Checking the Type

Let's verify what type of object NumPy creates.

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


## 4. Shape of an Array

Shape tells us how many rows and columns the array has.

In [5]:
print(arr.shape)

(5,)


Meaning of (5,)

This means:

5 elements
1 dimension

## 5. Number of Dimensions

In [6]:
print(arr.ndim)

1


## 6. Total Number of Elements

In [7]:
print(arr.size)

5


## 7. Mathematical Operations

In [9]:
print(arr + 2)
print(arr * 2)
print(arr ** 2)

[3 4 5 6 7]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


**Meaning**

This is where NumPy becomes magical.

Normal Python lists can’t do proper math like this.

NumPy applies operations to every element.

Example:

[1,2,3,4,5]+2=[3,4,5,6,7]

This is called vectorized operation.

Very important term.

It means operate on the whole array at once.

Faster and cleaner.

## Summary

Today I learned:

- what NumPy is
- why arrays are better than lists
- shape
- dimensions
- size
- basic operations

This is the foundation for AI, ML, and data science.