### Determinent of a matrix 

Determinant tells whether a matrix is invertible and gives scaling factor.

- det = 0 → not invertible 

- det ≠ 0 → invertible  



In [16]:
import numpy as np

A = np.array([[1,2],[3,4]])
np.linalg.det(A)

np.float64(-2.0000000000000004)

### Inverse of a Matrix

The inverse of a matrix A is another matrix A⁻¹ such that:

A @ A⁻¹ = I (Identity Matrix)



In [17]:

A = np.array([[1,2],[3,4]])
np.linalg.inv(A)


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Eigenvalues

Eigenvalues are special numbers that tell **how much a matrix stretches or shrinks a vector along specific directions (eigenvectors)**.

When a matrix acts on a vector, most vectors change direction — but eigenvectors only get scaled.

The scaling factor is the eigenvalue.

***Equation***

A v = λ v

Where:
- A = matrix  

- v = eigenvector

- λ = eigenvalue  

***Meaning***

- eigenvalues → scaling factors  

- eigenvectors → directions that do not rotate under transformation  

In [18]:
A = np.array([[1, 2],
              [3, 4]])

values, vectors = np.linalg.eig(A)

print(values)
print(vectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


### Norm (Vector Magnitude)

Norm is a measure of the **length or magnitude of a vector** in space.

It tells how far a vector is from the origin.


***Types of Norms***

***L1 Norm (Manhattan Norm)***

Sum of absolute values of vector components.

***Formula:***

||v||₁ = |x₁| + |x₂| + ... + |xₙ|


In [19]:
v = np.array([3, -4])

print(np.linalg.norm(v, ord=1))

7.0


***L2 Norm (Euclidean Norm)***

Straight-line distance from origin.

***Formula:***

||v||₂ = sqrt(x₁² + x₂² + ... + xₙ²)


In [20]:
v = np.array([3, -4])

print(np.linalg.norm(v, ord=2))

5.0


***Max Norm (Infinity Norm)***

Maximum absolute value in the vector.

***Formula:***

||v||∞ = max(|x₁|, |x₂|, ..., |xₙ|)

In [22]:
v = np.array([3, -4])

print(np.linalg.norm(v, ord=np.inf))

4.0


***Solving Linear Equations***

Used to solve equations of the form:

A x = b

Where:
- A = coefficient matrix

- x = unknown variables

- b = output values


So instead of computing inverse manually:

x = inv(A) @ b   ❌ (slow + unstable)

We directly solve:

A x = b   ✔ (fast + stable)

In [24]:
A = np.array([[2, 3],
              [1, 2]])

b = np.array([8, 5])

x = np.linalg.solve(A, b)

print(x)

[1. 2.]


### Singular Value Decomposition (SVD)

SVD breaks a matrix into 3 simpler matrices:

A = U × S × Vᵀ

Where:
- U = left singular vectors

- S = singular values (strength/importance)

- Vᵀ = right singular vectors


***Simple Intuition***

SVD:

- rotates data (U)

- scales it (S)

- rotates again (Vᵀ)


- S tells importance of directions

- used to compress or simplify data structure


***Important Note***

S is returned as a 1D array of singular values (not full diagonal matrix)

To rebuild:

np.diag(S)

In [27]:

A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

U, S, Vt = np.linalg.svd(A)

S_matrix = np.zeros((U.shape[1], Vt.shape[0]))
np.fill_diagonal(S_matrix, S)

print(U)
print(S)
print(Vt)

reconstructed = U @ S_matrix @ Vt

print(reconstructed)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]
