### Random Module

Random module is used to generate random numbers for simulations and ML tasks.



In [1]:
import numpy as np

np.random.seed(42)              # fixes randomness for reproducibility

print(np.random.rand(3))        # uniform random values [0,1)
print(np.random.randn(3))       # normal distribution (mean=0, std=1)
print(np.random.randint(1, 10, 5))  # random integers
print(np.random.choice([1,2,3,4], size=3))  # random selection

[0.37454012 0.95071431 0.73199394]
[-1.11188012  0.31890218  0.27904129]
[8 3 6 5 2]
[4 4 2]


### Shuffle

Shuffles array elements in-place.

In [5]:
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

[1 4 2 5 3]


### Advanced Aggregations & Stats

Functions that summarize data into statistical measures.

## Median

Middle value of sorted data.


In [6]:
arr = np.array([1, 2, 3, 100])
print(np.median(arr))

2.5


## Percentile

Value below which a percentage of data falls.

In [8]:
arr = np.array([1, 2, 3, 4, 5])

print(np.percentile(arr, 50))  # median
print(np.percentile(arr, 25))  # lower quarter
print(np.percentile(arr, 75))  # upper quarter

3.0
2.0
4.0


# Correlation Coefficient

Measures how strongly two variables move together.

***Value Range***

- +1 → perfect positive correlation 

- 0 → no correlation  

- -1 → perfect negative correlation  


In [10]:
x = np.array([1,2,3,4])
y = np.array([2,4,6,8])

print(np.corrcoef(x, y))

[[1. 1.]
 [1. 1.]]


# Covariance

Measures how two variables change together.

- Positive → both increase together  

- Negative → one increases, other decreases  

- Around 0 → no clear relationship  

***Formula***

cov(X,Y) = Σ (xi - mean(X)) (yi - mean(Y)) / n


In [11]:
x = np.array([1, 2, 3, 4])
y = np.array([8, 6, 4, 2])

cov = np.cov(x, y)

print(cov)

[[ 1.66666667 -3.33333333]
 [-3.33333333  6.66666667]]


# 3. Sorting & Unique Operations

Used to organize and analyze data.

## Sorting

Arranges elements in ascending order.

In [13]:
arr = np.array([3,1,5,2])

print(np.sort(arr))

[1 2 3 5]


# np.argsort( )

Returns the indices that would sort an array.


In [15]:
arr = np.array([3,1,5,2])

print(np.argsort(arr))

[1 3 0 2]


***Meaning***

`[1, 3, 0, 2]` means:

- smallest value is at index 1  

- next at index 3  

- next at index 0  

- last at index 2  

***Using Indices***


In [16]:
indices = np.argsort(arr)
print(arr[indices])

[1 2 3 5]


## Unique

Returns unique elements from array.


In [17]:
arr = np.array([1,2,2,3,3,3])

print(np.unique(arr))

[1 2 3]


## Bincount

Counts frequency of each integer value.


In [18]:
arr = np.array([1,2,2,3,3,3])

print(np.bincount(arr))

[0 1 2 3]


our array:

[1, 2, 2, 3, 3, 3]

Now count:

0 → 0 times

1 → 1 time

2 → 2 times

3 → 3 times

So result becomes:

[0, 1, 2, 3]