## 1. Basic Indexing and Slicing 

Indexing means accessing a single element using its position

Slicing means extracting a range of elements

In [1]:
import numpy as np 
arr = np.array([10,20,30,40,50,60])

print(arr[0])
print(arr[-1])
print(arr[:4])
print(arr[::-1])

10
60
[10 20 30 40]
[60 50 40 30 20 10]


## 2. Fancy Indexing

Fancy Indexing allows selecting specific elements by passing a list of indices



In [2]:
print(arr[[0,2,5]])
print(arr[[1,4,3]])

[10 30 60]
[20 50 40]


**Meaning**

Instead of continuous slicing, you choose exact positions.

Very useful when selecting specific columns/features later.

## 3. Boolean Indexing 

Boolean indexing is used to filter data based on the condition.

A most important Numpy feature 

In [3]:
print(arr>30)
print(arr[arr>30])

[False False False  True  True  True]
[40 50 60]


In [4]:
print(arr%20==0)
print(arr[arr%20==0])

[False  True False  True False  True]
[20 40 60]


**Meaning**

First expression:

arr > 30

returns:

[False False False True True True]

This is called a **boolean mask**.

Then:

arr[arr > 30]

uses that mask to filter values.

This is exactly how data filtering works in real ML preprocessing.

## 4. copy vs view

Numpy slicing usually returns a view not a completely new array.
which means that changes in sliced array can affect the original array.

In [26]:
A = np.array([1,2,3,4,5])
B = A[1:4]
B[0] = 100
print("original : ",A)
print("view : ",B)

original :  [  1 100   3   4   5]
view :  [100   3   4]


**Meaning**

This changes original array too.

Because b is a view.

**Fix**

for fixing it we will use copy method

In [27]:
C = A.copy()
C[0] = 99
print("original : ",A)
print("copy : ",C)

original :  [  1 100   3   4   5]
copy :  [ 99 100   3   4   5]


## 5. Reshape in Numpy

reshape( ) is used to change the shape of an array without changing its data.
it reorganizes the same elements into rows and columns.

**Syntax :**  arr.reshape(rows,columns)


**important rule** : totall no. of elements must remain the same.


In [7]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)

print("original : ",arr)
print("reshaped : ",reshaped)

original :  [1 2 3 4 5 6]
reshaped :  [[1 2 3]
 [4 5 6]]


In [8]:
print(arr.shape)
print(reshaped.shape)

(6,)
(2, 3)


**using -1**

it tells numpy to calculate dimension automatically


In [9]:
data = np.array([1,2,3,4,5,6,7,8])
auto = data.reshape(2,-1)
print(auto)

[[1 2 3 4]
 [5 6 7 8]]


Since total elements = 8 and rows = 2 so NumPy automatically makes it `(2, 4)`.

## 6. Flatten 

converts multiple dimension arrays to 1D

In [11]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
flattened = matrix.flatten()

print("flattened : ",flattened) 
print(flattened.shape)

flattened :  [1 2 3 4 5 6 7 8 9]
(9,)


## 7. Concatenation and Stacking

Numpy provides multiple ways to combine Arrays : 

concatenate() -->joins arrays in a single sequence


In [15]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])
con = np.concatenate((a1,a2))
print(con)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


vstack() -->stacks arrays vertically (row wise)


In [16]:
vstk = np.vstack((a1,a2))
print(vstk)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]



hstack() -->stacks arrays horizontally (column wise)

In [22]:
hstk = np.hstack((a1,a2))
print(hstk)

[[1 2 5 6]
 [3 4 7 8]]


## 8. Axis Concept

Axis tells numpy **The direction in which an operation should be performed**.



For a 2D Array :
[
    [1,2,3]
    [4,5,6]
]

Axis = 0 --> operation moves down the rows (column-wise)

Axis = 1 --> operation moves across the column (row-wise)

In [23]:
array = np.array([[1,2,3],[4,5,6]])
col_wise = array.sum(axis=0)
row_wise = array.sum(axis=1)
print("column wise : ",col_wise)
print("row wise : ",row_wise)

column wise :  [5 7 9]
row wise :  [ 6 15]


**Axis with concatenate**

supppose a 2D array then 

axis = 0 with concatenate means vstack

axis = 1 with concatenate means hstack

In [25]:
vstk = np.concatenate((a1,a2),axis=0)
print("vstack : \n",vstk)
hstk = np.concatenate((a1,a2),axis=1)
print("hstack : \n",hstk)

vstack : 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack : 
 [[1 2 5 6]
 [3 4 7 8]]
