## Broadcasting


Broadcasting allows operations on arrays of different shapes by automatically expanding dimensions.

***Rules***

***Rule 1: Compare shapes from right to left***

Shapes are aligned starting from the last dimension.

for example : (3,1)      (3,)




In [12]:
import numpy as np

***Rule 2: Dimensions must be equal OR 1***

Two dimensions are compatible if:
- they are equal, OR
- one of them is 1

***Rule 3: Missing dimensions treated as 1***


for example :   (3,) → (1,3) conceptually


***Rule 4: Dimension with size 1 expands***


for example :   (3,1) + (3,3) → (3,3)

In [24]:
A = np.array([[1],[2],[3]])
B = np.array([10,20,30])
A+B

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

now let's check a condition where it doesn't work

In [14]:
C = np.array([[1,2,3],[4,5,6]])
D = np.array([[10,20],[30,40]])
C+D

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

rules aren't satisfied here that's why boradcasting fails here

## Aggregation

 functions that reduce many values into one (or fewer) values

***Main Aggregation Functions***

np.sum()    ---->SUM

np.mean()   ---->MEAN

np.min()    ---->MINIMUM

np.max()    ---->MAXIMUM

np.std()    ---->STANDARD DEVIATION

np.var()    ---->VARIANCE

In [15]:
arr1 = np.array([1, 2, 3, 4, 5])

print(np.sum(arr1))   
print(np.mean(arr1))  
print(np.max(arr1))  
print(np.min(arr1))  
print(np.std(arr1))
print(np.var(arr1))

15
3.0
5
1
1.4142135623730951
2.0


### Matrix Multiplication

Matrix multiplication is an operation where each element of the result is obtained by multiplying rows of the first matrix with columns of the second matrix and summing them.


***Rule***

(m, n) @ (n, p) → (m, p)

Inner dimensions must match.

In [19]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

A @ B                 # or A.dot(B)   

array([[19, 22],
       [43, 50]])

***Difference: Matrix Multiplication vs Element-wise Multiplication***



***Element-wise Multiplication***

Each element is multiplied at the same position.


In [20]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

A * B

array([[ 5, 12],
       [21, 32]])

***Matrix Multiplication***

Row × column multiplication is performed and summed.


In [23]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([5, 6])

A.dot(B)

array([17, 39])