### Normalization   (Z-score Scaling)

Transforms data so it has: 

- mean = 0

- standard deviation = 1


It is also called **standardization**

***Formula***

X = (X - μ) / σ`

Where:

- μ = mean of data

  - σ = standard deviation 
  
***Intuition***

 Each value shows:
 
>how far it is from the mean in standard deviation units
 
    - Positive → above mean 
 
    - Negative → below mean
  
    - 0 → exactly mean  

***Use normalization when:***

- features have different scales 

- working with ML models like:  

    - linear regression  
    
    - logistic regression  
    
    - SVM   
    
    - neural networks  

In [ ]:
import numpy as np

X = np.array([10, 20, 30, 40])

X_norm = (X - np.mean(X)) / np.std(X)

print(X_norm)

print(np.mean(X_norm))
print(np.std(X_norm))   

[-1.34164079 -0.4472136   0.4472136   1.34164079]
0.0
1.0


### Min-Max Scaling


Min-Max Scaling transforms data into a fixed range, usually **0 to 1**.

***Formula***

X' = (X - min) / (max - min)

***Intuition***

- smallest value becomes 0 

- largest value becomes 1

- everything else gets squeezed between 0 and 1  


***When to use***

Use Min-Max scaling when:

- you need bounded values (0–1 range)  

- working with neural networks  

- using distance-based models (KNN, K-means)  


In [4]:

X = np.array([10, 20, 30, 40, 50])

X_scaled = (X - np.min(X)) / (np.max(X) - np.min(X))

print(X_scaled)


[0.   0.25 0.5  0.75 1.  ]


### Feature Combination

Creating new features by combining existing ones using mathematical operations.

Each new value represents a **relationship between two original features**, not an individual one.

Used when:

- single features are not strong enough

- interaction between features carries useful signal

- you want to capture hidden patterns in data

In [5]:
x = np.array([[2,3], [4,5], [6,7]])
new_feature = x[:,0] * x[:,1]
print(new_feature) 

[ 6 20 42]


***What is happening***

- `X[:, 0]` → first column → [2, 4, 6]  

- `X[:, 1]` → second column → [3, 5, 7]  

- Multiply row-wise → [2×3, 4×5, 6×7]

Result =      [6, 20, 42]

### Binary Feature Creation

Converting continuous values into binary signals (0/1) based on conditions.

Transforms continuous values into simple **yes/no signals**.

***Why it is used***

Used when:

- you need simple decision signals

- converting features into categories

- preparing data for ML models that prefer binary inputs


In [7]:
array = np.array([10, 20, 30, 40, 50])
bin_feature =(array>25).astype(int)
print(bin_feature)

[0 0 1 1 1]


### Data Transformation

Changing the scale or distribution of data to make it more suitable for analysis or machine learning.

Transforms data distribution without changing the number of features.

***Why it is used***

Used when:

- data is skewed (not evenly distributed)

- large values dominate small ones

- model performs better on transformed patterns



#### 1. Log Transformation

Reduces skewness and compresses large values.


In [9]:
X = np.array([1, 10, 100, 1000])

print(np.log(X))

[0.         2.30258509 4.60517019 6.90775528]


#### 2. Square Root Transformation

Reduces variance and smooths data.

In [11]:
X = np.array([1, 4, 9, 100])

print(np.sqrt(X))

[ 1.  2.  3. 10.]


#### 3. Exponential Transformation

Expands values and increases separation.

In [ ]:
X = np.array([1,2,3,4])
print(np.exp(X))

[ 2.71828183  7.3890561  20.08553692 54.59815003]
