## 1. Basic Indexing and Slicing 

Indexing means accessing a single element using its position

Slicing means extracting a range of elements

In [81]:
import numpy as np 
arra = np.array([10,20,30,40,50,60])

print(arra[0])
print(arra[-1])
print(arra[:4])
print(arra[::-1])

10
60
[10 20 30 40]
[60 50 40 30 20 10]


## 2D indexing and slicing

**Accessing single elements**

In [82]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix[0, 0])
print(matrix[1, 2])
print(matrix[2, 1])


1
6
8


## Row and Column Slicing

In [83]:
print(matrix[0, :])   # first row
print(matrix[:, 1])   # second column
print(matrix[0:2, 1:3])

[1 2 3]
[2 5 8]
[[2 3]
 [5 6]]


## 2. Fancy Indexing

Fancy Indexing allows selecting specific elements by passing a list of indices



In [84]:
print(arra[[0,2,5]])
print(arra[[1,4,3]])

[10 30 60]
[20 50 40]


**Meaning**

Instead of continuous slicing, you choose exact positions.

Very useful when selecting specific columns/features later.

## 3. Boolean Indexing 

Boolean indexing is used to filter data based on the condition.

One of the most important NumPy features. 

In [85]:
print(arra>30)
print(arra[arra>30])

[False False False  True  True  True]
[40 50 60]


In [86]:
print(arra%20==0)
print(arra[arra%20==0])

[False  True False  True False  True]
[20 40 60]


**Meaning**

First expression:

arr > 30

returns:

[False False False True True True]

This is called a **boolean mask**.

Then:

arr[arr > 30]

uses that mask to filter values.

This is exactly how data filtering works in real ML preprocessing.

## 4. copy vs view

Numpy slicing usually returns a view not a completely new array.
which means that changes in sliced array can affect the original array.

In [87]:
A = np.array([1,2,3,4,5])
B = A[1:4]
B[0] = 100
print("original : ",A)
print("view : ",B)

original :  [  1 100   3   4   5]
view :  [100   3   4]


**Meaning**

This changes original array too.

Because b is a view.

**Fix**

for fixing it we will use copy method

In [88]:
C = A.copy()
C[0] = 99
print("original : ",A)
print("copy : ",C)

original :  [  1 100   3   4   5]
copy :  [ 99 100   3   4   5]


# 5. np.where( )

Used for condition-based selection.

In [89]:
print(np.where(A%2==0, "even", "odd"))

['odd' 'even' 'odd' 'even' 'odd']


# 6. np.take( )

Used to take elements by index positions.

In [90]:
print(np.take(A, [0,2,4]))

[1 3 5]


# 7. np.put( )

Used to replace elements at specific positions.

In [91]:
np.put(A, [0,2,4], [99,88,77])
print(A)

[ 99 100  88   4  77]


# 8. np.choose( )

Select values based on index choices.

np.choose() selects column-wise by position.

In [92]:
choices = np.array([[1,2,3],[4,5,6],[7,8,9]])
index = [[0,2,1]]
print(np.choose(index, choices))

[[1 8 6]]


np.choose() selects values from multiple arrays based on index positions.

Index 0 selects from first row

Index 1 selects from second row

Index 2 selects from third row

## 9. Reshape in Numpy

reshape( ) is used to change the shape of an array without changing its data.
it reorganizes the same elements into rows and columns.

**Syntax :**  arr.reshape(rows,columns)


**important rule** : totall no. of elements must remain the same.


In [93]:
arra = np.array([1,2,3,4,5,6])
reshaped = arra.reshape(2,3)

print("original : ",arra)
print("reshaped : ",reshaped)

original :  [1 2 3 4 5 6]
reshaped :  [[1 2 3]
 [4 5 6]]


In [94]:
print(arra.shape)
print(reshaped.shape)

(6,)
(2, 3)


**using -1**

it tells numpy to calculate dimension automatically


In [95]:
data = np.array([1,2,3,4,5,6,7,8])
auto = data.reshape(2,-1)
print(auto)

[[1 2 3 4]
 [5 6 7 8]]


Since total elements = 8 and rows = 2 so NumPy automatically makes it `(2, 4)`.

## 10. Flatten 

converts multiple dimension arrays to 1D

In [96]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
flattened = matrix.flatten()

print("flattened : ",flattened) 
print(flattened.shape)

flattened :  [1 2 3 4 5 6 7 8 9]
(9,)


## 11. Concatenation and Stacking

Numpy provides multiple ways to combine Arrays : 

concatenate() -->joins arrays in a single sequence


In [97]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])
con = np.concatenate((a1,a2))
print(con)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


 **stack( )**

Stacks arrays along a new axis.

In [98]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
stacked = np.stack((a,b))
print(stacked)

[[1 2 3 4]
 [5 6 7 8]]


**vstack( )** -->stacks arrays vertically (row wise)


In [99]:
vstk = np.vstack((a,b))
print(vstk)

[[1 2 3 4]
 [5 6 7 8]]



**hstack( )** -->stacks arrays horizontally (column wise)

In [100]:
hstk = np.hstack((a,b))
print(hstk)

[1 2 3 4 5 6 7 8]


**dstack( )**

Depth stacking


Very useful for RGB image channels.

In [101]:
dstk = np.dstack((a,b))
print(dstk)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


## 12. Axis Concept

Axis tells numpy **The direction in which an operation should be performed**.



For a 2D Array :
[
    [1,2,3]
    [4,5,6]
]

Axis = 0 --> operation moves down the rows (column-wise)

Axis = 1 --> operation moves across the column (row-wise)

In [102]:
array = np.array([[1,2,3],[4,5,6]])
col_wise = array.sum(axis=0)
row_wise = array.sum(axis=1)
print("column wise : ",col_wise)
print("row wise : ",row_wise)

column wise :  [5 7 9]
row wise :  [ 6 15]


**Axis with concatenate**

supppose a 2D array then 

axis = 0 with concatenate means vstack

axis = 1 with concatenate means hstack

In [103]:
vstk = np.concatenate((a1,a2),axis=0)
print("vstack : \n",vstk)
hstk = np.concatenate((a1,a2),axis=1)
print("hstack : \n",hstk)

vstack : 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack : 
 [[1 2 5 6]
 [3 4 7 8]]


# 13. ravel( )


Also converts array into 1D.

**Difference from flatten( )**

- `flatten()` → copy

- `ravel()` → view (usually)

In [104]:
x = np.array([[1,2],[3,4]])
y = x.ravel()
y[0] = 100
print(x)

[[100   2]
 [  3   4]]


# 14. transpose( )

Swaps rows and columns.

In [105]:
arra = np.array([[1,2],[3,4],[5,7]])
print(arra.transpose())

[[1 3 5]
 [2 4 7]]


# 15. .T Shortcut

Shortcut for transpose.

In [106]:
print(arra.T)

[[1 3 5]
 [2 4 7]]


# 16. np.expand_dims( )

Adds a new dimension.

In [107]:
array1 = np.array([1,2,3,4,5])
ax0 = np.expand_dims(array1, axis=0)
ax1 = np.expand_dims(array1, axis=1)

print("original : ",array1)
print("expanded by axis = 0: ",ax0)
print("expanded by axis = 1: ",ax1)

original :  [1 2 3 4 5]
expanded by axis = 0:  [[1 2 3 4 5]]
expanded by axis = 1:  [[1]
 [2]
 [3]
 [4]
 [5]]


**shapes and dimensions of new arrays**


In [108]:
print(ax0.shape)

(1, 5)


In [109]:
print(ax0.ndim)

2


In [110]:
print(ax1.shape)

(5, 1)


In [111]:
print(ax1.ndim)

2


# 17. np.squeeze( )

Removes dimensions of size 1.

In [112]:
arr = np.array([[1,2,3,4,5,7]])
sqz = arr.squeeze()
print(sqz)

[1 2 3 4 5 7]


# 18. split( )

Split arrays into parts.

Important: total elements must be divisible by the number of splits.

In [113]:
parts = np.split(sqz,3)
print(parts)

[array([1, 2]), array([3, 4]), array([5, 7])]


# 19. hsplit( ) and vsplit( )

**np.hsplit() → Horizontal Split**

split column-wise
from left to right

In [114]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
parts = np.hsplit(matrix, 2)
print(parts)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


**np.vsplit() → Vertical Split**

This splits row-wise
from top to bottom.

So it cuts rows into chunks.

In [115]:
matrix2 = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])
parts = np.vsplit(matrix2, 2)
print(parts)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
